In [199]:
# Primeiramente vamos importar as bibliotecas usadas neste estudo de caso, como segue.
import numpy as np #biblioteca com recursos para álgebra linear
import pandas as pd # processamento dos dados, carga de arquivo CSV e de I/O
import json
from sklearn import *
import sklearn.model_selection as model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_validate


#import matplotlib.pyplot as plt
#from collections import Counter
#from sklearn.cross_validation import train_test_split

In [200]:
# Nós utilizaremos neste caso, o dataset (conjunto de dados) phishing.csv, disponível aqui pra você.
# A origem deste arquivo csv foi 'https://archive.ics.uci.edu/ml/datasets/phishing+websites'
#
# Primeiro, vamos testar o carregamento do arquivo CSV.
# Não vamos usar com detalhes a biblioteca pandas neste caso, mas esse trecho de código ajuda a entender o arquivo com o conjunto de dados.
df = pd.read_csv('kaggle/input/phishing/phishing.csv')
#df.info() #apresenta os metadados do arquivo csv
#df.tail(10)
#df.describe()

In [201]:
# Vamos agora carregar o dataset que iremos utilizar na variável np.
training_data = np.genfromtxt('kaggle/input/phishing/phishing.csv', delimiter=',', dtype=np.int32)
print(training_data) #para ver os dados na variável.

[[-1  1  1 ...  1 -1 -1]
 [ 1  1  1 ...  1  1 -1]
 [ 1  0  1 ...  0 -1 -1]
 ...
 [ 1 -1  1 ...  0  1 -1]
 [-1 -1  1 ...  1  1 -1]
 [-1 -1  1 ...  1 -1 -1]]


In [202]:
# Identificando as entradas (todos os atributos, exceto o último) e as saídas (o último atributo):
inputs = training_data[:,:-1]
outputs = training_data[:,-1]

print(inputs.shape)
print(outputs.shape)

(11055, 30)
(11055,)


In [203]:
# Dividindo o dataset em treino e teste.
#training_inputs = inputs[:2000]
#training_outputs = outputs[:2000]
#testing_inputs = inputs[2000:]
#testing_outputs = outputs[2000:]

# dividing the dataset into training and testing:
training_inputs, testing_inputs, training_outputs, testing_outputs = model_selection.train_test_split(inputs, outputs, test_size=0.2)

print(training_inputs.shape)
print(testing_inputs.shape)
print(training_outputs.shape)
print(testing_outputs.shape)


(8844, 30)
(2211, 30)
(8844,)
(2211,)


In [204]:
classifier1 = LogisticRegression()
classifier2 = DecisionTreeClassifier()
classifier3 = RandomForestClassifier(max_depth=18, n_estimators=30, max_features=30, random_state=20)

In [205]:
# Treinando os classificadores.
classifier1.fit(training_inputs, training_outputs)
classifier2.fit(training_inputs, training_outputs)
classifier3.fit(training_inputs, training_outputs)

RandomForestClassifier(max_depth=18, max_features=30, n_estimators=30,
                       random_state=20)

In [206]:
# Fazendo as predições.
predictions1 = classifier1.predict(testing_inputs)
predictions2 = classifier2.predict(testing_inputs)
predictions3 = classifier3.predict(testing_inputs)

In [207]:
# Calculando a acurácia para o modelo de detecção de phishing.
accuracy1 = 100.0 * accuracy_score(testing_outputs, predictions1)
accuracy2 = 100.0 * accuracy_score(testing_outputs, predictions2)
accuracy3 = 100.0 * accuracy_score(testing_outputs, predictions3)

In [208]:
# Imprimindo a acurácia para o modelo de detecção de phishing.
print ("A acurácia para o classificador de regressão logística sobre os dados de teste é: " +str(accuracy1))
print ("A acurácia para o classificador de árvore de decisão sobre os dados de teste é: " +str(accuracy2))
print ("A acurácia para o classificador de Random Forest sobre os dados de teste é: " +str(accuracy3))

A acurácia para o classificador de regressão logística sobre os dados de teste é: 92.94436906377204
A acurácia para o classificador de árvore de decisão sobre os dados de teste é: 96.47218453188603
A acurácia para o classificador de Random Forest sobre os dados de teste é: 97.24106739032112
